version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    tty: true
    env_file:
      - .envs/.db-psql
    environment:
      - POSTGRES_DB=prod_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=thepassword
    ports:
      - 5432:5432
    expose:
      - "5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-project
    restart: unless-stopped
    volumes:
      - ./django-project:/opt/django/django-project
      - static:/opt/django/django-project/apps/static
      - media:/opt/django/django-project/apps/media
    expose:
      - 80
    env_file:
      - ./.envs/.django
    depends_on:
      - db

    environment:
      SERVICE_NAME: django-project
      SERVICE_TAGS: web
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 80
      # Enable this if you want to have https/ssl support.
      # Don't enable this if you use cloudflare
      # LETSENCRYPT_HOST: yourdomain.com
      # LETSENCRYPT_EMAIL: youremail@yourdomain.com

  #Enable this if you want to config your db with easy UI
  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080
  #'''x

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  static:
    external: true
  media:
    external: true
